version: '3'
services:
  db:
    image: postgres:9.6.1
    container_name: chatapp_db
    environment:
      - POSTGRES_DB=chatapp_development
    ports:
      - "5432:5432"
  redis:
      image: redis
      container_name: chatapp_redis
      ports:
        - "6379:6379"